require("plugins.nvim-lspconfig")
require("plugins.mason")
require("plugins.conform")
require("plugins.colorscheme")
require("plugins.nvim-tree")
require("plugins.vim-visual-multi")
require("plugins.neogit")
require("plugins.vim-tmux-navigator")
